// Generated by BUCKLESCRIPT VERSION 5.0.4, PLEASE EDIT WITH CARE

import * as React from "react";

function App(Props) {
  var name = Props.name;
  return React.createElement(React.Fragment, undefined, React.createElement("h1", undefined, "Hello " + (name + "!")), React.createElement("div", undefined, "Look ", React.createElement("a", {
                      href: "https://parceljs.org",
                      rel: "noopener noreferrer",
                      target: "_blank"
                    }, "here"), " for more info about Parcel."));
}

var make = App;

export {
  make ,
  
}
/* react Not a pure module */
