// Generated by BUCKLESCRIPT VERSION 5.0.4, PLEASE EDIT WITH CARE

import * as React from "react";
import * as ReactDOMRe from "reason-react/src/ReactDOMRe.js";
import * as App$ReasonmlTodoMvc from "./App.bs.js";

ReactDOMRe.renderToElementWithId(React.createElement(App$ReasonmlTodoMvc.make, {
          name: "Parcel"
        }), "app");

export {
  
}
/*  Not a pure module */
